//! # KeyCodes - Identificadores de Teclas
//!
//! Mapeamento de teclas para o RedstoneOS.

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyCode {
    None = 0,
    Esc,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    N0,
    Minus,
    Equal,
    Backspace,
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    OpenBracket,
    CloseBracket,
    Enter,
    Control,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Quote,
    Backtick,
    Shift,
    Backslash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Period,
    Slash,
    Alt,
    Space,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    NumLock,
    ScrollLock,
    Home,
    Up,
    PageUp,
    KeypadMinus,
    Left,
    Center,
    Right,
    KeypadPlus,
    End,
    Down,
    PageDown,
    Insert,
    Delete,
    F11,
    F12,
}

impl KeyCode {
    pub fn from_scancode(scancode: u8) -> Self {
        match scancode & 0x7F {
            0x01 => KeyCode::Esc,
            0x02 => KeyCode::N1,
            0x03 => KeyCode::N2,
            0x04 => KeyCode::N3,
            0x05 => KeyCode::N4,
            0x06 => KeyCode::N5,
            0x07 => KeyCode::N6,
            0x08 => KeyCode::N7,
            0x09 => KeyCode::N8,
            0x0A => KeyCode::N9,
            0x0B => KeyCode::N0,
            0x0C => KeyCode::Minus,
            0x0D => KeyCode::Equal,
            0x0E => KeyCode::Backspace,
            0x0F => KeyCode::Tab,
            0x10 => KeyCode::Q,
            0x11 => KeyCode::W,
            0x12 => KeyCode::E,
            0x13 => KeyCode::R,
            0x14 => KeyCode::T,
            0x15 => KeyCode::Y,
            0x16 => KeyCode::U,
            0x17 => KeyCode::I,
            0x18 => KeyCode::O,
            0x19 => KeyCode::P,
            0x1A => KeyCode::OpenBracket,
            0x1B => KeyCode::CloseBracket,
            0x1C => KeyCode::Enter,
            0x1D => KeyCode::Control,
            0x1E => KeyCode::A,
            0x1F => KeyCode::S,
            0x20 => KeyCode::D,
            0x21 => KeyCode::F,
            0x22 => KeyCode::G,
            0x23 => KeyCode::H,
            0x24 => KeyCode::J,
            0x25 => KeyCode::K,
            0x26 => KeyCode::L,
            0x27 => KeyCode::Semicolon,
            0x28 => KeyCode::Quote,
            0x29 => KeyCode::Backtick,
            0x2A => KeyCode::Shift,
            0x2B => KeyCode::Backslash,
            0x2C => KeyCode::Z,
            0x2D => KeyCode::X,
            0x2E => KeyCode::C,
            0x2F => KeyCode::V,
            0x30 => KeyCode::B,
            0x31 => KeyCode::N,
            0x32 => KeyCode::M,
            0x33 => KeyCode::Comma,
            0x34 => KeyCode::Period,
            0x35 => KeyCode::Slash,
            0x38 => KeyCode::Alt,
            0x39 => KeyCode::Space,
            0x3A => KeyCode::CapsLock,
            0x3B => KeyCode::F1,
            0x3C => KeyCode::F2,
            0x3D => KeyCode::F3,
            0x3E => KeyCode::F4,
            0x3F => KeyCode::F5,
            0x40 => KeyCode::F6,
            0x41 => KeyCode::F7,
            0x42 => KeyCode::F8,
            0x43 => KeyCode::F9,
            0x44 => KeyCode::F10,
            0x47 => KeyCode::Home,
            0x48 => KeyCode::Up,
            0x49 => KeyCode::PageUp,
            0x4A => KeyCode::KeypadMinus,
            0x4B => KeyCode::Left,
            0x4C => KeyCode::Center,
            0x4D => KeyCode::Right,
            0x4E => KeyCode::KeypadPlus,
            0x4F => KeyCode::End,
            0x50 => KeyCode::Down,
            0x51 => KeyCode::PageDown,
            0x52 => KeyCode::Insert,
            0x53 => KeyCode::Delete,
            0x57 => KeyCode::F11,
            0x58 => KeyCode::F12,
            _ => KeyCode::None,
        }
    }

    pub fn to_char(&self, shifted: bool) -> Option<char> {
        match self {
            KeyCode::Space => Some(' '),
            KeyCode::A => Some(if shifted { 'A' } else { 'a' }),
            KeyCode::B => Some(if shifted { 'B' } else { 'b' }),
            KeyCode::C => Some(if shifted { 'C' } else { 'c' }),
            KeyCode::D => Some(if shifted { 'D' } else { 'd' }),
            KeyCode::E => Some(if shifted { 'E' } else { 'e' }),
            KeyCode::F => Some(if shifted { 'F' } else { 'f' }),
            KeyCode::G => Some(if shifted { 'G' } else { 'g' }),
            KeyCode::H => Some(if shifted { 'H' } else { 'h' }),
            KeyCode::I => Some(if shifted { 'I' } else { 'i' }),
            KeyCode::J => Some(if shifted { 'J' } else { 'j' }),
            KeyCode::K => Some(if shifted { 'K' } else { 'k' }),
            KeyCode::L => Some(if shifted { 'L' } else { 'l' }),
            KeyCode::M => Some(if shifted { 'M' } else { 'm' }),
            KeyCode::N => Some(if shifted { 'N' } else { 'n' }),
            KeyCode::O => Some(if shifted { 'O' } else { 'o' }),
            KeyCode::P => Some(if shifted { 'P' } else { 'p' }),
            KeyCode::Q => Some(if shifted { 'Q' } else { 'q' }),
            KeyCode::R => Some(if shifted { 'R' } else { 'r' }),
            KeyCode::S => Some(if shifted { 'S' } else { 's' }),
            KeyCode::T => Some(if shifted { 'T' } else { 't' }),
            KeyCode::U => Some(if shifted { 'U' } else { 'u' }),
            KeyCode::V => Some(if shifted { 'V' } else { 'v' }),
            KeyCode::W => Some(if shifted { 'W' } else { 'w' }),
            KeyCode::X => Some(if shifted { 'X' } else { 'x' }),
            KeyCode::Y => Some(if shifted { 'Y' } else { 'y' }),
            KeyCode::Z => Some(if shifted { 'Z' } else { 'z' }),
            KeyCode::N1 => Some(if shifted { '!' } else { '1' }),
            KeyCode::N2 => Some(if shifted { '@' } else { '2' }),
            KeyCode::N3 => Some(if shifted { '#' } else { '3' }),
            KeyCode::N4 => Some(if shifted { '$' } else { '4' }),
            KeyCode::N5 => Some(if shifted { '%' } else { '5' }),
            KeyCode::N6 => Some(if shifted { '^' } else { '6' }),
            KeyCode::N7 => Some(if shifted { '&' } else { '7' }),
            KeyCode::N8 => Some(if shifted { '*' } else { '8' }),
            KeyCode::N9 => Some(if shifted { '(' } else { '9' }),
            KeyCode::N0 => Some(if shifted { ')' } else { '0' }),
            KeyCode::Minus => Some(if shifted { '_' } else { '-' }),
            KeyCode::Equal => Some(if shifted { '+' } else { '=' }),
            KeyCode::Comma => Some(if shifted { '<' } else { ',' }),
            KeyCode::Period => Some(if shifted { '>' } else { '.' }),
            KeyCode::Slash => Some(if shifted { '?' } else { '/' }),
            KeyCode::Semicolon => Some(if shifted { ':' } else { ';' }),
            KeyCode::Quote => Some(if shifted { '"' } else { '\'' }),
            KeyCode::OpenBracket => Some(if shifted { '{' } else { '[' }),
            KeyCode::CloseBracket => Some(if shifted { '}' } else { ']' }),
            KeyCode::Backslash => Some(if shifted { '|' } else { '\\' }),
            KeyCode::Backtick => Some(if shifted { '~' } else { '`' }),
            KeyCode::Enter => Some('\n'),
            _ => None,
        }
    }
}
